name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & run tests
        run: |
          cd automation/web-ui
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          # složka pro report (kdyby neexistovala)
          mkdir -p reports
          pytest   # pytest.ini už zajistí HTML report

      - name: Upload pytest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: automation/web-ui/reports/report.html
          retention-days: 7
